language: node_js
os:
  - linux
node_js:
  - "5.1.0"
branches:
  only:
    - master
    - develop
sudo: required
before_install:
      - 'sudo apt-get update -y -qq'
      - 'sudo apt-get install -y -qq nsis'
      - 'npm install -g bower grunt grunt-cli'
      - 'npm install'
install:
  - 'npm install'
script:
  - 'grunt'
